# Generated by Django 4.1.6 on 2023-02-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_alter_conversation_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
