# Generated by Django 4.1.6 on 2023-02-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_alter_conversation_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='content',
            field=models.TextField(verbose_name='Treść wiadomomści'),
        ),
    ]
