# Generated by Django 4.1.6 on 2023-02-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_alter_conversation_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('modified_at',)},
        ),
    ]
