# Generated by Django 4.1.6 on 2023-02-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0005_alter_conversation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('-modified_at',)},
        ),
    ]
